apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::537983829639:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-hXKdxMCxzP1V\n
    \ username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n
    \ rolearn: arn:aws:iam:537983829639:role/UdacityFlaskDeployCBKubectlRole\n  username:
    build \n"
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-09T11:29:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "9067"
  uid: 521c342a-2ad0-4eac-a1b7-86a2c461689f
